### ISSUE TITLE
Add `oldValue` to `onChange` event handlers

### ISSUE THREAD

**Issue by macdonst** [enhance-dev/enhance-base-element#6]
I've run into a situation where in my `onChange` handler I need access to the old value of the attribute. Can we update the on change event handler to be:

```javascript
onChange(value, oldValue)
```

Basically, change:

```diff
  attributeChangedCallback(name, oldValue, newValue) {
    if (oldValue !== newValue) {
      const fun = `${kebabToCamel(name)}Changed`
      if (this[fun]) {
-        this[fun](newValue)
+        this[fun](newValue, oldValue)
      }
    }
  }
```

Use case, I have a chart component who's type attribute is currently `bar` and the type is changed to `column`. I have to remove `bar` from the list of CSS classes that control the appearance of the component while adding `column`.

**Comment by kristoferjoseph** [comment]
Sounds like a reasonable change.
